# dataset
nps: 2000
ns: 10
dl: 2
dd: 6
nl: 2
p: 'gauss'
act: 'none'
uncentered: true
# noisy: 0.1
noisy: 0.0

# model args
# n_layers: 1
n_layers: 2
hidden_dim: 50
activation: 'lrelu'
ica: false
tcl: false
fastica: true

# learning
a: 100
b: 1
c: 0
d: 10
gamma: 0
# epochs: 1
no_scheduler: true
scheduler_tol: 20
anneal: false
anneal_epoch: 20

# more configs
shuffle: true
one_hot: true
checkpoint: true
simple_mixing: true
terms: false
# g_simple MLP:
g: true
discrete: true
identity: false
stop: 50
early: false
# cond_thresh: 2
same_var: false
simple_prior: true
simple_logv: true
fix_v: false
logvar: -6.8
custom_data: false
std_lower: 0.5
std_upper: 3.0
diag: false
percentile: 20

# Tracking
track_prior: true
# wandb: true
wandb: false
tensorboard: false
comet: false
plot_freq: 500
# cannot be smaller than check_freq
check_freq: 1
verbose: false
track_grad_norm: true

# Normalizations
norm_mean_data: false
norm_logl_data: false

norm_f: false
norm_A_data: false

norm_prior_mean: false
norm_logl: false

# # optimization
# lbfgs: true
# gd: false
# tol: 0.0001
# lr: 1
# history_size: 200
# # max_iter: 30
# max_iter: 1000