# dataset
nps: 1000
# nps: 8000
ns: 40
dl: 2
dd: 2
nl: 2
p: 'gauss'
act: 'none'
uncentered: true
noisy: 0.1

# model args
n_layers: 2
hidden_dim: 50
activation: 'lrelu'
ica: true
tcl: false

# learning
a: 100
b: 1
c: 0
d: 10
gamma: 0
batch_size: 40000
# batch_size: 50
epochs: 10
# epochs: 50
no_scheduler: true
scheduler_tol: 20
anneal: false
anneal_epoch: 20

# more configs
shuffle: true
one_hot: true
checkpoint: true
simple_mixing: true
terms: false
# g_simple MLP:
g: true
discrete: false
check_freq: 1
identity: true
stop: 50
early: false
# cond_thresh: 2
same_var: false
simple_prior: true
tensorboard: false
comet: false
simple_logv: true
wandb: true
fix_v: false
norm_f: true
logvar: -6.8
norm_A_data: true
custom_data: false
lbfgs: true
# max_iter: 100
max_iter: 30
# history_size: 100
# history_size: 1000
# history_size: 1
history_size: 200
lr: 1
# lr: 0.8