# dataset
nps: 8000
# ns: 120
ns: 40
dl: 5
dd: 5
nl: 2
p: 'gauss'
act: 'none'
uncentered: true
noisy: 0

# model args
n_layers: 2
hidden_dim: 50
activation: 'lrelu'
ica: true
tcl: false

# learning
a: 100
b: 1
c: 0
d: 10
gamma: 0
# lr: 0.1
lr: 0.001
# lr: 0.0001
batch_size: 50
# epochs: 150
# epochs: 300
# epochs: 3
epochs: 200
no_scheduler: true
scheduler_tol: 20
anneal: false
anneal_epoch: 20

# more configs
shuffle: true
one_hot: true
checkpoint: true
simple_mixing: true
terms: true
# terms: false
# g_simple MLP:
g: true
discrete: true
check_freq: 1
# identity: false
identity: true
early: false
stop: 20
cond_thresh: 2
same_var: false
simple_prior: true
tensorboard: false
comet: false
simple_logv: true
wandb: true
fix_v: true
norm_f: false
# logvar: 0.1
# logvar: -2.3
# logvar: -4.5
logvar: -6.8
norm_A_data: false
custom_data: true